[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Dependencies
[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.9.6" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.3.0" }

[rpc_endpoints]
cali = "https://api.calibration.node.glif.io/rpc/v1"
filecoin_calibration = "https://api.calibration.node.glif.io/rpc/v1"

[etherscan]
cali = { key = "", url = "https://calibration.filfox.info/api" }
